FROM apache/airflow:3.2.1-python3.12

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY ./pyproject.toml /opt/airflow

COPY ./src /usr/python/lib/python3.12/src

COPY ./constants /usr/python/lib/python3.12/constants

COPY ./data_quality /usr/python/lib/python3.12/data_quality

USER root
RUN uv pip install -r /opt/airflow/pyproject.toml --python /usr/python/bin/python3.12
USER airflow

USER root
RUN mkdir -p /app/gx && chown -R airflow:root /app/gx
USER airflow